name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

    steps:
      # 1. リポジトリのソースコードを取得
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Terraformをセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Terraformを初期化（バックエンドとしてS3を設定）
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -reconfigure \
          -backend-config="bucket=$TF_STATE_BUCKET" \
          -backend-config="key=project2/terraform.tfstate" \
          -backend-config="region=us-west-2"

      # 4. Terraformでリソースを削除（Destroy）
      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve